version: '3'

services:
  app:
    build:
      context: ./test/dummy
    image: ruby:3.1.4
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - bundler:/usr/local/bundle/

volumes:
  bundler:
